# Generated by Django 5.2.1 on 2025-11-21 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_rename_username_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=20)),
                ('semester', models.IntegerField()),
                ('department', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('toughness', models.JSONField(default=dict)),
                ('study_hours', models.JSONField(default=dict)),
                ('sleep_hours', models.JSONField(default=dict)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
