# Generated by Django 5.2.1 on 2025-11-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
