# Generated by Django 5.2.1 on 2025-11-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='regno',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
