# Generated by Django 5.2.1 on 2025-11-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
    ]
